namespace: kube-system

image:
  repository: themagicalkarp/kube-janitor
  tag: v0.0.1
  pullPolicy: IfNotPresent

kubejanitor:
  dryrun: false
  expiration: 60
  namespace: ""
  annotation: kube.janitor.io
  verbose: true

cron:
  schedule: "*/1 * * * *"

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 100Mi
  # requests:
  #   cpu: 50m
  #   memory: 50Mi
