kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "chart.fullname" . }}
  namespace: {{ .Values.namespace }}